
sudo hostname svr1a
hostname | sudo tee /etc/hostname
cat << EOF | sudo tee /etc/netplan/01_net.yaml

network:
  ethernets:
    eth0:
      dhcp4: no
    eth1:
      dhcp4: no
  bonds:
    bond0:
      macaddress: 52:54:00:69:62:3c
      interfaces:
        - eth0
        - eth1
      parameters:
         mode: 802.3ad
      addresses: [ 192.168.101.1/24, fc00:dead:beef:a101::1000:1/64]
      gateway4: 192.168.101.254
      gateway6:  fc00:dead:beef:a101::1
EOF