---
- name: set vrf configuration
  hosts: all
  connection: local
  gather_facts: no

  vars:
    user: admin
    passwd: pass01

  tasks:
    - name: load vrf configuration
      juniper.device.config:  
        template: "./set_vrf.j2"
        format: text
        load: merge
        vars: "{{ lookup('file','vars_' + inventory_hostname + '.yaml') | from_yaml}}"
