network:
  version: 2
  ethernets:
    eth0:
      addresses: 
      - 192.168.30.2/24
      - "fc00:dead:beef:aa30::1000:2/64"
      routes:
      - to: 0.0.0.0/0
        via: "192.168.30.254"
      - to: "::/0"
        via: "fc00:dead:beef:aa30::1"
