---
- name: Get Device Facts
  hosts:
    - all
  connection: local
  gather_facts: no
  vars:
    username: admin
    password: pass01
  tasks:
    - name: Retrieve facts from devices running Junos OS
      juniper.device.facts:  
        savedir: ./result
        user: "{{ username }}"
        passwd: "{{ password }}"
    - name: Print version
      debug:
        var: junos.version