---
- name: Upload config into router
  hosts: 
  - all
  vars:
    username: admin
    password: pass01
  connection: local
  gather_facts: no
  tasks:
    - name: upload config into router
      juniper.device.config:
        user: "{{ username }}"
        passwd: "{{ password }}"
        # template: underlay_bgp.j2
        src: "conf/{{inventory_hostname}}.conf"
        config_mode: "exclusive"
        load: "merge"
        format: "text"


                  