hostname sw4
user admin group administrators password ciphertext AQBapd3BWm8Uk8/3zXPWMSwMGuCAnwrk6f1HAldAhSe+SjJBYgAAAPTi2CwzjpoXyMKrcrkUBcpJfm1S0zn6biTGaUTCxiCBGfqo/w6oZKfz/21FGwtza2H8h9ytNVLqQtyc/sol8bpzY+b3v/tEDwky5cD/SmiE5bkKThIkt5EhU1cVk7jVN3Lf
!
!
!
!
!
!
user admin authorized-key ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCnl7viJOzermvpAVgKw70Ldc/zyOdZ66K5JilIFjHUmURtz95tusGKtOF6KcoGy6Q58KkoMngr/3vAleMsucVW8vZN1mZh9Z4UcmlQ+nWCUK1sDGFX1198sHgTQUdzpP0Zbmd4Oj/WN9EH7Z7OP3NkJwuAtTogw3RMDyOTwQeInL+Ay/DAW4QV23TPTu+0+fI8zD/+GabA/o8aKsAnl6Lhmtrx4bBzQsYMULvFHmqZk9Hkm2jsDnSUW187vdBzNjxwANY45Bvn4xsmrl98uBGtRFDaYCgMHQodQUnQI6lvNF+d/HJa5AU2WfnIOBtveTXyDfA0b1rDDrFBMwMCQ1O0CvZbhQOjnESAeChY+0As6HbLQa0LO9YjkSmPUrNOPXLs8pv64fDgaJsnGKqsghl2eSgkHAr/HgxN4ByDDOJB3oRj9sXbCJVy+2LPH1XLiljn53AiOA6Orm5E2HaElaaaalww3lIoL2f7+mePZemnklvrtSaGmszTKxbAbLKz8Fk= irzan@home2
ssh server vrf mgmt
vlan 1,21-23
evpn
    vlan 21
        rd auto
        route-target export auto
        route-target import auto
    vlan 22
        rd auto
        route-target export auto
        route-target import auto
    vlan 23
        rd auto
        route-target export auto
        route-target import auto
interface mgmt
    no shutdown
    ip static 192.168.250.14/24
interface 1/1/1
    no shutdown
    mtu 9000
    ip mtu 9000
    ip address 10.1.255.133/31
    ip ospf 1 area 0.0.0.0
    ip ospf network point-to-point
interface 1/1/2
    no shutdown
    mtu 9000
    ip mtu 9000
    ip address 10.1.255.135/31
    ip ospf 1 area 0.0.0.0
    ip ospf network point-to-point
interface 1/1/5
    no shutdown
    mtu 9000
    no routing
    vlan trunk native 1
    vlan trunk allowed all
interface loopback 0
    ip address 10.1.255.4/32
    ip ospf 1 area 0.0.0.0
interface vxlan 1
    source ip 10.1.255.4
    no shutdown
    vni 10021
        vlan 21
    vni 10022
        vlan 22
    vni 10023
       vlan 23
!
!
!
!
!
router ospf 1
    router-id 10.1.255.4
    area 0.0.0.0
router bgp 4200000002
    neighbor 10.1.255.3 remote-as 4200000002
    neighbor 10.1.255.3 update-source 10.1.255.4
    address-family l2vpn evpn
        neighbor 10.1.255.3 send-community both
        neighbor 10.1.255.3 activate
    exit-address-family
!
https-server vrf mgmt
