---
spine1:
  interfaces:
  - ge-0/0/0
  - ge-0/0/1
  - ge-0/0/2
  - ge-0/0/3
  router_id: 10.1.10.1
  local_as: 65001
  as_list: 65000-65100
  loopback_ipv6: fc00:dead:beef:10::1/128
  overlay:
      local_as: 4200065001
      local_addr: fc00:dead:beef:10::1
      neighbors:
      - addr: fc00:dead:beef:10::3
        as: 4200065003
      - addr: fc00:dead:beef:10::4
        as: 4200065004
      - addr: fc00:dead:beef:10::5
        as: 4200065005
      - addr: fc00:dead:beef:10::6
        as: 4200065006
spine2:
  interfaces:
  - ge-0/0/0
  - ge-0/0/1
  - ge-0/0/2
  - ge-0/0/3
  router_id: 10.1.10.2
  local_as: 65002
  as_list: 65000-65100
  loopback_ipv6: fc00:dead:beef:10::2/128
  overlay:
      local_as: 4200065002
      local_addr: fc00:dead:beef:10::2
      neighbors:
      - addr: fc00:dead:beef:10::3
        as: 4200065003
      - addr: fc00:dead:beef:10::4
        as: 4200065004
      - addr: fc00:dead:beef:10::5
        as: 4200065005
      - addr: fc00:dead:beef:10::6
        as: 4200065006
leaf1:
  interfaces:
  - ge-0/0/0
  - ge-0/0/1
  router_id: 10.1.10.3
  local_as: 65003
  as_list: 65000-65100
  loopback_ipv6: fc00:dead:beef:10::3/128
  overlay:
      local_as: 4200065003
      local_addr: fc00:dead:beef:10::3
      neighbors:
      - addr: fc00:dead:beef:10::1
        as: 4200065001
      - addr: fc00:dead:beef:10::2
        as: 4200065002
leaf2:
  interfaces:
  - ge-0/0/0
  - ge-0/0/1
  router_id: 10.1.10.4
  local_as: 65004
  as_list: 65000-65100
  loopback_ipv6: fc00:dead:beef:10::4/128
  overlay:
      local_as: 4200065004
      local_addr: fc00:dead:beef:10::4
      neighbors:
      - addr: fc00:dead:beef:10::1
        as: 4200065001
      - addr: fc00:dead:beef:10::2
        as: 4200065002
leaf3:
  interfaces:
  - ge-0/0/0
  - ge-0/0/1
  router_id: 10.1.10.5
  local_as: 65005
  as_list: 65000-65100
  loopback_ipv6: fc00:dead:beef:10::5/128
  overlay:
      local_as: 4200065005
      local_addr: fc00:dead:beef:10::5
      neighbors:
      - addr: fc00:dead:beef:10::1
        as: 4200065001
      - addr: fc00:dead:beef:10::2
        as: 4200065002
leaf4:
  interfaces:
  - ge-0/0/0
  - ge-0/0/1
  router_id: 10.1.10.6
  local_as: 65006
  as_list: 65000-65100
  loopback_ipv6: fc00:dead:beef:10::6/128
  overlay:
      local_as: 4200065006
      local_addr: fc00:dead:beef:10::6
      neighbors:
      - addr: fc00:dead:beef:10::1
        as: 4200065001
      - addr: fc00:dead:beef:10::2
        as: 4200065002




