system {
    host-name r2;
    root-authentication {
        encrypted-password "$6$6f2kHzLr$Fnq.P/WTZQwxuINAitTzaSrGlmimznxgM1L3bHDOE/T85FcFdu3qlTCzve1Ru2BrSYeYBOQyA0PVCB6WlteKE/"; ## SECRET-DATA
    }
    login {
        user admin {
            uid 2001;
            class super-user;
            authentication {
                encrypted-password "$6$NWINpIG3$9imW330oxmhdnYXh5AQ51E.kSa5afMNVYjRY8m1c4bMe2.toZBFwXLaj/B/0XxkzguADkHWvi3dpl4qjR.cbb."; ## SECRET-DATA
            }
        }
    }
    services {
        ssh {
            sftp-server;
        }
    }
    syslog {
        file interactive-commands {
            interactive-commands any;
        }
        file messages {
            any notice;
            authorization info;
        }
    }
}
chassis {
    aggregated-devices {
        ethernet {
            device-count 4;
        }
    }
}
interfaces {
    ge-0/0/0 {
        flexible-vlan-tagging;
        encapsulation flexible-ethernet-services;
        unit 101 {
            vlan-id 101;
            family inet {
                address 10.1.102.1/24;
            }
            family iso;
            family inet6 {
                address fc00:dead:beef:102::1/64;
            }
        }
    }
    ge-0/0/1 {
        gigether-options {
            802.3ad ae0;
        }
    }
    ge-0/0/2 {
        gigether-options {
            802.3ad ae0;
        }
    }
    ae0 {
        mtu 9000;
        aggregated-ether-options {
            lacp {
                active;
            }
        }
        unit 0 {
            family inet {
                address 10.1.255.5/31;
            }
            family iso;
            family inet6;
        }
    }
    fxp0 {
        unit 0 {
            family inet {
                address 192.168.110.102/24;
            }
        }
    }
    lo0 {
        unit 0 {
            family inet {
                address 10.1.255.102/32;
            }
            family iso {
                address 49.0001.0001.0002.00;
            }
            family inet6 {
                address fc00:dead:beef:ffff::2/128;
            }
        }
    }
}
protocols {
    isis {
        interface ge-0/0/0.101 {
            passive;
        }
        interface ae0.0 {
            point-to-point;
        }
        interface lo0.0 {
            passive;
        }
    }
    lldp {
        interface ae0;
    }
}
